spring:
  datasource:
    url: jdbc:sqlserver://${DATABASE_HOST:localhost}:${DATABASE_PORT:1433};databaseName=${DATABASE_NAME:master}
    username: ${DATABASE_USER:sa}
    password: ${DATABASE_PASSWORD:PasswordnyaSA2018}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        default_catalog: ${DATABASE_NAME:master}
        default_schema: ${DATABASE_SCHEMA:default}
        format_sql: true
        enable_lazy_load_no_trans: true
        id:
          new_generator_mappings: false
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        globally_quoted_identifiers: true
        temp:
          use_jdbc_metadata_defaults: false
    database: sql_server
  flyway:
    encoding: UTF-8
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration/sqlserver-2017
    schemas: Default,OAuth,Auth,Resources,Components
    clean-disabled: false
    clean-on-validation-error: true
    connect-retries: 3
  queries:
    authentication: select * from auth.authentication(?)
    authorization: select * from auth.authorization(?)

