spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:tabeldata_auth}
    username: ${DATABASE_USER:tabeldata_auth}
    password: ${DATABASE_PASSWORD:tabeldata_auth}
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        id:
          new_generator_mappings: false
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        globally_quoted_identifiers: true
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    encoding: UTF-8
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration/postgresql
    schemas: public,oauth,auth,resource,component
    clean-disabled: false
    clean-on-validation-error: true
    connect-retries: 3
