version: '3.7'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=tabeldata_auth
      - POSTGRES_USER=tabeldata_auth
      - POSTGRES_DB=tabeldata_auth
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-server-network
volumes:
  postgres_data:
networks:
  auth-server-network:
